version: "3.3"

services:
  mariadb:
    image: 'mariadb:latest'
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'studentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
